import burger from './modules/burger.js';
import popup from './modules/popup.js';
import accordionSmooth from './modules/accordion-smooth.js';
import productSlider from './modules/product-slider.js';
import counter from './modules/counter.js';
import sectionSlider from './modules/sectionSlider.js';
import accordionFooterBtn from './modules/accordionFooter.js';
import productAddCart from './modules/productAddCart.js';
import maxChars from './modules/maxChars.js';
